### ISSUE TITLE
[YUNO] why you no implement it

### ISSUE THREAD

**Issue by yuhsiang** [amsul/react-translated#1]

**Comment by amsul** [comment]
@yuhsiang 😂 

All in due time bud. This package is a little tricky to extract from my current project. I'll do it in bits and pieces as I get time.

**Comment by amsul** [comment]
@yuhsiang just for you, I made some time.. and now here you go: https://github.com/amsul/react-translated#react-translated

💪

**Comment by yuhsiang** [comment]
Wow!
@amsul You are react native master!
