### ISSUE TITLE
Strings containing asterisks

### ISSUE THREAD

**Issue by jcmnunes** [amsul/react-translated#11]
I'm not finding the best way to do the following:

I need to translate strings containing `*` characters. Since  `*` are used to mark bold text, they are stripped from the translation strings and are not rendered.

Is there a way to escape asterisks? How can I translate strings containing `*`?

**Comment by amsul** [comment]
@jcmnunes thanks for bringing it to my attention!

I just published a new release that handles escaped characters: https://github.com/amsul/react-translated/releases/tag/v2.4.0
