### ISSUE TITLE
How to use translate() in methods?

### ISSUE THREAD

**Issue by hosembafer** [amsul/react-translated#9]

**Comment by hosembafer** [comment]
Problem solved. I bind it to window.translate() in reactjs, and global.translate() in react-native, closing.

**Comment by hosembafer** [comment]
@amsul, for example, I'm using Toast.show() from 'react-native-root-toast' in my RN app.

**Comment by amsul** [comment]
@hosembafer I recently released a new version where you can do:

```jsx
ReactTranslated.getTranslated({
  text: 'Hello {firstName}!',
  data: { firstName: 'Rafael' },
  translation: {
    en: 'Hello {firstName}!',
    fr: 'Bonjour {firstName}!',
  },
  language: 'en',
})
```
